project_id = "ihgzllefbkzqnomsviwh"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = [
  "https://ihgzllefbkzqnomsviwh.supabase.co",
  "http://localhost:8080",
  "http://localhost:8081", 
  "http://localhost:3000",
  "http://localhost:5173",
  "http://localhost:3000/auth/callback",
  "http://localhost:8080/auth/callback",
  "http://localhost:8081/auth/callback",
  "https://ihgzllefbkzqnomsviwh.supabase.co/auth/v1/callback"
]
jwt_expiry = 3600
enable_signup = true

[db]
shadow_port = 54320

[functions.hello-world]
verify_jwt = true

[functions.email-service]
verify_jwt = true

[functions.send-email-notification]
verify_jwt = true

[functions.create-payment-session]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.verify-payment]
verify_jwt = true

[storage]
enabled = true

[studio]
enabled = true
port = 54323
api_url = "http://localhost:54321"