project_id = "ihgzllefbkzqnomsviwh"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://ihgzllefbkzqnomsviwh.supabase.co"]
jwt_expiry = 3600
inactivity_timeout = 0
refresh_token_rotation_enabled = true
secure_session_cookie = false
enable_signup = true

[db]
shadow_port = 54320
import_maps = ["deno.land/x/postgres@v0.17.0/mod.ts"]

[edge_functions]
enabled = true
inspector_port = 8000

[functions.hello-world]
verify_jwt = false

[functions.create-payment-session]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[storage]
enabled = true
bucket_limit = 100
max_file_size_limit = 52428800
image_transformation_enabled = true

[studio]
enabled = true
port = 54323
api_url = "http://localhost:54321"